# Generated by Django 5.0.6 on 2024-07-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
