# Generated by Django 5.0.6 on 2024-07-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
    ]
